---
title: "Analysis on Investor Behaviour"
author: "Dea Avega Editya"
date: "8/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(tidyverse)
library(readr)
library(stringr)
library(lubridate)

bonds <- read.csv("data/FR0087.csv", header = F) %>% 
  mutate(date = as_date(substr(V5, 1, 6)), series = V2, bid_no = V1, yield = V3, bid = V4, bidder = V6, bidder_code = V8, 
         inv = gsub("\\s", "", V8), group = case_when(V10 == "CB" ~ "CB", TRUE ~ "non-CB"), custody = V11, alloted_unit = V12, proceed = V13, acr_int = V14) %>% 
  mutate(ivt = sub('.*-', '', inv), type = substr(bidder_code, 1, 2)) %>% 
  mutate(location = case_when(bidder %in% c("CITIBANK  N.A.", "KC JPMORGAN CHASE BANK  N.A.", "DEUTSCHE BANK  A.G.", "STANDCHART BANK") ~ "foreign", TRUE ~ "resident"),
         investor = case_when(
    ivt == "00" ~ bidder, TRUE ~ ivt)
          ) %>% 
  mutate(investor_type = case_when(substr(bidder_code, 4, 5) == "IB" ~ "investment bank", 
                                   substr(bidder_code, 4, 5) == "PF" ~ "pension fund",
                                   substr(bidder_code, 4, 5) == "SC" ~ "securities company",
                                   substr(bidder_code, 4, 5) == "IS" ~ "insurance")) %>% 
  mutate(investor = case_when(investor == "DanareksaSeku" ~ "BRI DANAREKSA SEKURITAS",
                              tolower(substr(investor, 1, 8)) == tolower("MandiriS") ~ "PT. MANDIRI SEKURITAS",
                              tolower(investor) == tolower("Trimegah") ~ "PT. TRIMEGAH SEKURITAS INDONESIA",
                              
                             tolower(substr(investor, 1, 6)) == tolower("Bahana") ~ "PT. BAHANA SEKURITAS",
                          TRUE ~ investor)) %>% 
  mutate(bidder_type = case_when(
    bidder %in% c("PT. MANDIRI SEKURITAS", "BRI DANAREKSA SEKURITAS", "PT Bank Mandiri (Persero), Tbk.", "PT Bank Negara Indonesia (Persero), Tbk.", "PT Bank Rakyat Indonesia, Tbk.") ~ "state-owned", TRUE ~ "private"
  )) %>% 
  select(-V1, -V2, -V3, -V4, -V6, -V5, -V7, -V8, -V9, -V10, -V11, -V12, -V13, -V14, -inv, -type, -ivt) %>% 
  as_tibble()

###
unique(bonds$investor_type)
typeof(bonds$investor_type)
foreign <- bonds %>% filter(bidder_type == "foreign")
```

There are several category of investors:
1. Investment Bank
2. Securities Company
3. Pension Fund
4. Insurance

```{r}
bonds %>% 
  select(investor_type, yield, alloted_unit) %>% 
  filter(yield > 0, alloted_unit > 0) %>% 
  ggplot(aes(x = investor_type, y = yield))+
  geom_boxplot()


bonds %>% 
  select(investor_type, yield, alloted_unit) %>%
  group_by(investor_type) %>% 
  filter(yield > 0, alloted_unit > 0) %>% 
  ggplot(aes(x = investor_type, y = yield))+
  geom_boxplot()


bonds %>% 
  select(bidder_type, yield, alloted_unit) %>%
  group_by(bidder_type) %>% 
  filter(yield > 0, alloted_unit > 0) %>% 
  ggplot(aes(x = bidder_type, y = yield))+
  geom_boxplot()
```

```{r}
bonds %>% 
  filter(investor_type == "Insurance") %>% 
summary()

securities_comp <- bonds %>% 
  filter(investor_type == "Securities Company")
  
```

Insurance ~ Investment Bank
Pension fund < IB
Securities Comp tend to more than IB

